MyBlog/urls.py
from django.contrib import admin
from django.urls import path, re_path,include


from blog import views

from django.views.static import serve
from django.conf import settings

from blog import urls as blog_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('^reg', views.register),                           # 注册
    re_path('^check_username_exist/$', views.check_username_exist),     # 校验用户名是否已经被注册的接口
    re_path('^login', views.login),                             # 登陆
    re_path('^logout', views.logout),  # 注销
    re_path('^index', views.index),                             # 主页
    re_path('^pc-geetest/register', views.get_geetest),      # 极验滑动验证码 获取验证码的url
    # media相关的路由设置
    re_path('^media/(?P<path>.*)$', serve, {"document_root": settings.MEDIA_ROOT}),

    re_path('^blog/', include(blog_urls)),
]

blog/urls.py
from django.urls import path, re_path
from blog import views


urlpatterns = [

    re_path('comment/$', views.comment),  # 评论
    re_path('poll/$', views.poll),  # 点赞 踩

    re_path('^(\w+)/article/(\d+)/$', views.article_detail),  # 文章详情

    re_path('(\w+)/$', views.home), # home(request, username)
    # url(r'(\w+)/article/(\d+)/$', views.article_detail),  # 文章详情  article_detail(request, xiaohei, 1)


]

blog/models.py
from django.db import models

# Create your models here.

from django.contrib.auth.models import AbstractUser,auth


class UserInfo(AbstractUser):
    """
    用户信息表
    """
    nid = models.AutoField(primary_key=True)
    phone = models.CharField(max_length=11, null=True, unique=True)
    avatar = models.FileField(upload_to="avatars/", default="avatars/default.png", verbose_name="头像")
    create_time = models.DateTimeField(auto_now_add=True)

    blog = models.OneToOneField(to="Blog", to_field="nid", null=True,on_delete=models.CASCADE)

    def __str__(self):
        return self.username

    class Meta:
        verbose_name = "用户"                 # admin后台显示中文设置
        verbose_name_plural = verbose_name      # 复数设置


class Blog(models.Model):
    """
    博客信息
    """
    nid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=64)  # 个人博客标题
    site = models.CharField(max_length=32, unique=True)  # 个人博客后缀
    theme = models.CharField(max_length=32)  # 博客主题

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "blog站点"
        verbose_name_plural = verbose_name


class Category(models.Model):
    """
    个人博客文章分类
    """
    nid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=32)  # 分类标题
    blog = models.ForeignKey(to="Blog", to_field="nid",on_delete=models.CASCADE)  # 外键关联博客，一个博客站点可以有多个分类

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "文章分类"
        verbose_name_plural = verbose_name


class Tag(models.Model):
    """
    标签
    """
    nid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=32)  # 标签名
    blog = models.ForeignKey(to="Blog", to_field="nid",on_delete=models.CASCADE)    # 所属博客

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "标签"
        verbose_name_plural = verbose_name


class Article(models.Model):
    """
    文章
    """
    nid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=50, verbose_name="文章标题")  # 文章标题
    desc = models.CharField(max_length=255)  # 文章描述
    create_time = models.DateTimeField()  # 创建时间

    # 评论数
    comment_count = models.IntegerField(verbose_name="评论数", default=0)
    # 点赞数
    up_count = models.IntegerField(verbose_name="点赞数", default=0)
    # 踩
    down_count = models.IntegerField(verbose_name="踩数", default=0)

    category = models.ForeignKey(to="Category", to_field="nid", null=True,on_delete=models.CASCADE)
    user = models.ForeignKey(to="UserInfo", to_field="nid",on_delete=models.CASCADE)
    tags = models.ManyToManyField(  # 中介模型
        to="Tag",
        through="Article2Tag",
        through_fields=("article", "tag"),  # 注意顺序！！！
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "文章"
        verbose_name_plural = verbose_name


class ArticleDetail(models.Model):
    """
    文章详情表
    """
    nid = models.AutoField(primary_key=True)
    content = models.TextField()
    article = models.OneToOneField(to="Article", to_field="nid",on_delete=models.CASCADE)

    class Meta:
        verbose_name = "文章详情"
        verbose_name_plural = verbose_name


class Article2Tag(models.Model):
    """
    文章和标签的多对多关系表
    """
    nid = models.AutoField(primary_key=True)
    article = models.ForeignKey(to="Article", to_field="nid",on_delete=models.CASCADE)
    tag = models.ForeignKey(to="Tag", to_field="nid",on_delete=models.CASCADE)

    def __str__(self):
        return "{}-{}".format(self.article.title, self.tag.title)

    class Meta:
        unique_together = (("article", "tag"),)
        verbose_name = "文章-标签"
        verbose_name_plural = verbose_name


class ArticleUpDown(models.Model):
    """
    点赞表
    """
    nid = models.AutoField(primary_key=True)
    user = models.ForeignKey(to="UserInfo", null=True,on_delete=models.CASCADE)
    article = models.ForeignKey(to="Article", null=True,on_delete=models.CASCADE)
    is_up = models.BooleanField(default=True)

    class Meta:
        unique_together = (("article", "user"),)
        verbose_name = "文章点赞"
        verbose_name_plural = verbose_name


class Comment(models.Model):
    """
    评论表
    """
    nid = models.AutoField(primary_key=True)
    article = models.ForeignKey(to="Article", to_field="nid",on_delete=models.CASCADE)
    user = models.ForeignKey(to="UserInfo", to_field="nid",on_delete=models.CASCADE)
    content = models.CharField(max_length=255)  # 评论内容
    create_time = models.DateTimeField(auto_now_add=True)
    parent_comment = models.ForeignKey("self", null=True, blank=True,on_delete=models.CASCADE)  # null=True 数据库可以为空； blank=True 在django admin里面可以不填

    def __str__(self):
        return self.content

    class Meta:
        verbose_name = "评论"
        verbose_name_plural = verbose_name

blog/forms.py
"""
bbs用到的form类
"""

from django import forms
from django.core.exceptions import ValidationError
from blog import models


# 定义一个注册的form类
class RegForm(forms.Form):
    username = forms.CharField(
        max_length=16,
        label="用户名",
        error_messages={
            "max_length": "用户名最长16位",
            "required": "用户名不能为空",
        },
        widget=forms.widgets.TextInput(
            attrs={"class": "form-control"},
        )
    )

    password = forms.CharField(
        min_length=6,
        label="密码",
        widget=forms.widgets.PasswordInput(
            attrs={"class": "form-control"},
            render_value=True,
        ),
        error_messages={
            "min_length": "密码至少要6位！",
            "required": "密码不能为空",
        }
    )

    re_password = forms.CharField(
        min_length=6,
        label="确认密码",
        widget=forms.widgets.PasswordInput(
            attrs={"class": "form-control"},
            render_value=True,
        ),
        error_messages={
            "min_length": "确认密码至少要6位！",
            "required": "确认密码不能为空",
        }
    )

    email = forms.EmailField(
        label="邮箱",
        widget=forms.widgets.EmailInput(
            attrs={"class": "form-control"},

        ),
        error_messages={
            "invalid": "邮箱格式不正确！",
            "required": "邮箱不能为空",
        }
    )

    # 重写username字段的局部钩子
    def clean_username(self):
        username = self.cleaned_data.get("username")
        is_exist = models.UserInfo.objects.filter(username=username)
        if is_exist:
            # 表示用户名已经注册
            self.add_error("username", ValidationError("用户名已经存在"))

    # 重写username字段的局部钩子
    def clean_email(self):
        email = self.cleaned_data.get("email")
        is_exist = models.UserInfo.objects.filter(email=email)
        if is_exist:
            # 表示用户名已经注册
            self.add_error("email", ValidationError("邮箱已经注册"))

    # 重写全局的钩子函数，对确认密码做校验
    def clean(self):
        password = self.cleaned_data.get("password")
        re_password = self.cleaned_data.get("re_password")

        if re_password and re_password != password:
            self.add_error("re_password", ValidationError("两次密码不一致"))

        else:
            return self.cleaned_data

templates/article_detail.html
{% extends 'base.html' %}
{% block page-main %}

    <div class="article-detail">
        <h1>{{ article.title }}</h1>
        <p>{{ article.articledetail.content|safe }}</p>
    </div>

    <!-- 点赞与踩的图片copy 样式文件在base.html文件中-->
    <div id="div_digg">
        <div class="diggit digg" onclick="">
            <span class="diggnum" id="digg_count">0</span>
        </div>
        <div class="buryit digg" onclick="">
            <span class="burynum" id="bury_count">0</span>
        </div>
        <div class="clear"></div>
        <div class="diggword" id="digg_tips">
        </div>
    </div>

    <div style="margin-top: 100px;">
        <hr>
    </div>

    <p>评论楼</p>
    <ul class="list-group comment_list">
        {% for comment in comment_list %}
            <li class="list-group-item comment_item">
                <div>
                    <a href="">#{{ forloop.counter }}楼</a>&nbsp;&nbsp;&nbsp;
                    <span>{{ comment.create_time|date:"Y-m-d H：i" }}</span>&nbsp;&nbsp;
                    <a href="">{{ comment.user.username }}</a>
                    <a class="pull-right reply" username="{{ comment.user.username }}" pk="{{ comment.pk }}">回复</a>
                </div>
                <div>
                    {% if comment.parent_comment_id %}
                    <div class="parent_comment_info well">
                        <a href="">@{{ comment.parent_comment.user.username }}</a>&nbsp;&nbsp;
                        <span>{{ comment.parent_comment.content }}</span>
                    </div>
                    {% endif %}
                <div><p>{{ comment.content }}</p></div>
                </div>
            </li>
        {% endfor %}
    </ul>

    <div class="comment region">
        <div class="row">

            <div class="col-md-7">
                <p>昵称：<input type="text" id="tbCommentAuthor" class="author" disabled="disabled" size="50"
                             value="{{ request.user.username }}"></p>
                <p>评论内容：</p>
                <textarea name="" id="comment_text" cols="60" rows="10"></textarea>
                <button class="btn btn-default pull-right comment_btn">提交</button>
            </div>
        </div>
    </div>

    <div id="info" article_id="{{ article.pk }}" username="{{ request.user.username }}"></div>
    {% csrf_token %}
    <script>
        $("#div_digg .digg").click(function () {

            if ("{{ request.user.username }}") {
                // 判断是赞还是灭
                var is_up = $(this).hasClass("diggit");
                var article_id = "{{ article.pk }}";
                // var article_id = $("#info").attr("article_id");
                var user_id = "{{ request.user.pk }}";

                $.ajax({
                    url: "/blog/poll/",
                    type: "post",
                    data: {
                        is_up: is_up,
                        article_id: article_id,
                        user_id: user_id,
                        csrfmiddlewaretoken: $("[name='csrfmiddlewaretoken']").val()
                    },
                    success: function (data) {
                        console.log(data);

                        if (data.state) {// 赞或者灭成功

                            if (is_up) {
                                var val = $("#digg_count").text();
                                val = parseInt(val) + 1;
                                $("#digg_count").text(val);
                            } else {
                                var val = $("#bury_count").text();
                                val = parseInt(val) + 1;
                                $("#bury_count").text(val);
                            }
                        }
                        else {    // 重复提交

                            if (data.fisrt_action) {
                                $("#digg_tips").html("您已经推荐过");
                            } else {
                                $("#digg_tips").html("您已经反对过");
                            }

                            setTimeout(function () {
                                $("#digg_tips").html("")
                            }, 1000)

                        }

                    }
                })
            }
        });
    </script>

    <script>
        var pid = "";
        // 绑定提交评论事件
        $(".comment_btn").click(function () {
            if ("{{ request.user.username }}") {
                var article_id = $("#info").attr("article_id");
                if (pid) { // 获取子评论内容
                    var index = $("#comment_text").val().indexOf("\n");
                    var content = $("#comment_text").val().slice(index + 1);  // 参数不加表示取到最后
                } else {
                    var content = $("#comment_text").val();
                }

                $.ajax({
                    url: "/blog/comment/",
                    type: "post",
                    data: {
                        article_id: article_id,
                        content: content,
                        pid: pid,
                        csrfmiddlewaretoken: $("[name='csrfmiddlewaretoken']").val()
                    },
                    success: function (data) {
                        console.log(data);
                        if (data.state) { // 提交功能

                            // 清空
                            $("#comment_text").val("");
                        } else { // 提交失败

                        }

                    }

                })
            }
        });
        // 绑定回复按钮事件
        $(".comment_item .reply").click(function () {
            $(".comment_text").focus();
            var val = "@" + $(this).attr("username") + "\n";
            $("#comment_text").val(val);
            pid = $(this).attr("pk")
        })
    </script>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ blog.title }}</title>

    <link rel="stylesheet" href="/static/mystyle2.css">
    <link rel="stylesheet" href="/static/plugins/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/plugins/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="/static/theme/{{ blog.theme }}">
    <link rel="stylesheet" href="/static/my_css/article_detail.css">
    <script src="/static/jquery-3.3.1.js"></script>


</head>
<body>

<div class="header">
    <p>{{ blog.title }}</p>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-3 ">

            {% load my_tags %}
            {% get_left_menu username %}
        </div>
            <div class="col-md-8">

                {% block page-main %}

                {% endblock %}

            </div>

    </div>
</div>


<script src="/static/jquery-3.3.1.js"></script>
<script src="/static/plugins/bootstrap/js/bootstrap.min.js"></script>

</body>
</html>

templates/bookstrap.html
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <meta name="renderer" content="webkit">
    <title>Title</title>

    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- HTML5 shim 和 Respond.js 是为了让 IE8 支持 HTML5 元素和媒体查询（media queries）功能 -->
    <!-- 警告：通过 file:// 协议（就是直接将 html 页面拖拽到浏览器中）访问页面时 Respond.js 不起作用 -->
    <!--[if lt IE 9]>
      <script src="https://cdn.jsdelivr.net/npm/html5shiv@3.7.3/dist/html5shiv.min.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/respond.js@1.4.2/dest/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <h1>你好，世界！</h1>

    <form>
  <div class="form-group">
    <label for="exampleInputEmail1">Email address</label>
    <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Email">
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Password</label>
    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
  </div>
  <div class="form-group">
    <label for="exampleInputFile">File input</label>
    <input type="file" id="exampleInputFile">
    <p class="help-block">Example block-level help text here.</p>
  </div>
  <div class="checkbox">
    <label>
      <input type="checkbox"> Check me out
    </label>
  </div>
  <button type="submit" class="btn btn-default">Submit</button>
</form>





    <!-- jQuery (Bootstrap 的所有 JavaScript 插件都依赖 jQuery，所以必须放在前边) -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@1.12.4/dist/jquery.min.js"></script>
    <!-- 加载 Bootstrap 的所有 JavaScript 插件。你也可以根据需要只加载单个插件。 -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js"></script>
  </body>
</html>

templates/get_left_menu.html
<div class="panel panel-primary">
    <div class="panel-heading">文章分类</div>
    <div class="panel-body">
        {% for category in category_list %}
            <p>{{ category.title }}({{ category.c }})</p>  <!--{{ category.article_set.all.count }}-->
        {% endfor %}

    </div>
</div>


<div class="panel panel-info">
    <div class="panel-heading">文章标签</div>
    <div class="panel-body">
        {% for tag in tag_list %}
            <p>{{ tag.title }}({{ tag.c }})</p>
        {% endfor %}
    </div>
</div>

<div class="panel panel-info">
    <div class="panel-heading">日期归档</div>
    <div class="panel-body">
        {% for archive in archive_list %}
            <p>{{ archive.archive_ym }}({{ archive.c }})</p>
        {% endfor %}
    </div>
</div>

templates/home.html
{% extends 'base.html' %}

{% block page-main %}

    <!-- 个人博客列表 开始 -->
            <div class="article_list">
                {% for article in article_list %}
                    <div class="article">
                        <p class="article-title"><a href="/blog/{{ article.user.username }}/article/{{ article.pk }}/">{{ article.title }}</a></p>

                        <!-- bookstrip 媒体对象 开始 -->
                        <div class="media">
                            <div class="media-left">
                                <a href="#">
                                    <img class="media-object author-img" src="/media/{{ article.user.avatar }}"
                                         alt="...">
                                </a>
                            </div>
                            <div class="media-body">
                                {{ article.desc }}
                            </div>
                        </div>
                        <div class="article-footer">
                            <span><a href="/blog/{{ article.user.username }}/">{{ article.user.username }}</a>发布于</span>
                            <span>{{ article.create_time|date:'Y-m-d H:i:s' }}</span>
                            <span class="glyphicon glyphicon-comment">评论（{{ article.comment_count }}）</span>
                            <span class="glyphicon glyphicon-thumbs-up">点赞（{{ article.up_count }}）</span>

                        </div>
                        <hr>
                    </div>
                {% endfor %}
            </div>
            <!-- 个人博客列表 结束 -->

{% endblock %}

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>index</title>
    <link rel="stylesheet" href="/static/plugins/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/plugins/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="/static/mystyle.css">

</head>
<body>
<script src="/static/jquery-3.3.1.js"></script>
<script src="/static/plugins/bootstrap/js/bootstrap.min.js"></script>


<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">The Blog</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
                <li><a href="#">Link</a></li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                {% if request.user.username %}
                    <li><a href="#">{{ request.user.username }}</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false">个人中心<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Action</a></li>
                            <li><a href="#">Another action</a></li>
                            <li><a href="#">Something else here</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="/logout/">注销</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li><a href="/login/">登陆</a></li>
                    <li><a href="/reg/">注册</a></li>
                {% endif %}

            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>
<div class="container">
    <div class="row">

        <div class="col-md-2">

            <div class="panel panel-primary">
                <div class="panel-heading">左侧广告位一</div>
                <div class="panel-body">
                    Panel content
                </div>
            </div>

            <div class="panel panel-info">
                <div class="panel-heading">左侧广告位二</div>
                <div class="panel-body">
                    Panel content
                </div>
            </div>

        </div>

        <div class="col-md-8">
            <!-- 文章列表 开始 -->
            <div class="article_list">
                {% for article in article_list %}
                    <div class="article">
                        <h3>{{ article.title }}</h3>

                        <!-- bookstrip 媒体对象 开始 -->
                        <div class="media">
                            <div class="media-left">
                                <a href="#">
                                    <img class="media-object author-img" src="/media/{{ article.user.avatar }}" alt="...">
                                </a>
                            </div>
                            <div class="media-body">
                                {{ article.desc }}
                            </div>
                        </div>
                        <div class="article-footer">
                            <span><a href="/blog/{{ article.user.username }}/">{{ article.user.username }}</a>发布于</span>
                            <span>{{ article.create_time|date:'Y-m-d H:i:s' }}</span>
                            <span class="glyphicon glyphicon-comment">评论（{{ article.comment_count }}）</span>
                            <span class="glyphicon glyphicon-thumbs-up">点赞（{{ article.up_count }}）</span>

                        </div>
                            <hr>
                    </div>
                {% endfor %}
            </div>
            <!-- 文章列表 结束 -->
        </div>

        <div class="col-md-2">
            <div class="panel panel-primary">
                <div class="panel-heading">右侧广告位一</div>
                <div class="panel-body">
                    Panel content
                </div>
            </div>

            <div class="panel panel-info">
                <div class="panel-heading">右侧广告位二</div>
                <div class="panel-body">
                    Panel content
                </div>
            </div>
        </div>
    </div>
</div>

</body>
</html>

templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>欢迎注册</title>
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/mystyle.css">
</head>
<body>

<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <form novalidate autocomplete="off" action="/reg/" method="post" class="form-horizontal reg-form"
                  enctype="multipart/form-data">
                {% csrf_token %}

                <div class="form-group">
                    <label for="{{ form_obj.username.id_for_label }}"
                           class="col-sm-2 control-label">{{ form_obj.username.label }}</label>
                    <div class="col-sm-8">
                        {{ form_obj.username }}
                        <span class="help-block">{{ form_obj.username.errors.0 }}</span>
                    </div>
                </div>

                <div class="form-group">
                    <label for="{{ form_obj.password.id_for_label }}"
                           class="col-sm-2 control-label">{{ form_obj.password.label }}</label>
                    <div class="col-sm-8">
                        {{ form_obj.password }}
                        <span class="help-block">{{ form_obj.password.errors.0 }}</span>
                    </div>
                </div>

                <div class="form-group">
                    <label for="{{ form_obj.re_password.id_for_label }}"
                           class="col-sm-2 control-label">{{ form_obj.re_password.label }}</label>
                    <div class="col-sm-8">
                        {{ form_obj.re_password }}
                        <span class="help-block">{{ form_obj.re_password.errors.0 }}</span>
                    </div>
                </div>

                <div class="form-group">
                    <label for="{{ form_obj.email.id_for_label }}"
                           class="col-sm-2 control-label">{{ form_obj.email.label }}</label>
                    <div class="col-sm-8">
                        {{ form_obj.email }}
                        <span class="help-block">{{ form_obj.email.errors.0 }}</span>
                    </div>
                </div>

                <div class="form-group">
                    <label
                            class="col-sm-2 control-label">头像</label>
                    <div class="col-sm-8">
                        <label for="id_avatar"><img id="avatar-img" src="/static/img/default.png" alt=""></label>
                        <input accept="image/*" type="file" name="avatar" id="id_avatar" style="display: none">
                        <span class="help-block"></span>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="button" class="btn btn-success" id="reg-submit">注册</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>


<script src="/static/jquery-3.3.1.js"></script>
<script src="/static/bootstrap/js/bootstrap.min.js"></script>
<script>
    // 找到头像的input标签绑定change事件
    $("#id_avatar").change(function () {
        // 1. 创建一个读取文件的对象
        var fileReader = new FileReader();
        // 取到当前选中的头像文件
        // console.log(this.files[0]);
        // 读取你选中的那个文件
        fileReader.readAsDataURL(this.files[0]);  // 读取文件是需要时间的
        fileReader.onload = function () {
            // 2. 等上一步读完文件之后才 把图片加载到img标签中
            $("#avatar-img").attr("src", fileReader.result);
        };
    });

// AJAX提交注册的数据
    $("#reg-submit").click(function () {
        // 取到用户填写的注册数据，向后端发送AJAX请求
        var formData = new FormData();
        formData.append("username", $("#id_username").val());
        formData.append("password", $("#id_password").val());
        formData.append("re_password", $("#id_re_password").val());
        formData.append("email", $("#id_email").val());
        formData.append("avatar", $("#id_avatar")[0].files[0]);
        formData.append("csrfmiddlewaretoken", $("[name='csrfmiddlewaretoken']").val());

        $.ajax({
            url: "/reg/",
            type: "post",
            processData: false,
            contentType: false,
            data: formData,
            success: function (data) {
                if (data.status) {
                    // 有错误就展示错误
                    // console.log(data.msg);
                    // 将报错信息填写到页面上
                    $.each(data.msg, function (k, v) {
                        // console.log("id_"+k, v[0]);
                        // console.log($("#id_"+k));
                        $("#id_" + k).next("span").text(v[0]).parent().parent().addClass("has-error");
                    })

                } else {
                    // 没有错误就跳转到指定页面
                    location.href = data.msg;
                }
            }
        })
    });

    // 将所有的input框绑定获取焦点的事件，将所有的错误信息清空
    $("form input").focus(function () {
        $(this).next().text("").parent().parent().removeClass("has-error");
    });

    // 给username input 框绑定一个失去焦点的事件，失去焦点之后就校验用户名是否已经被注册
    {#$("#id_username").blur(function () {#}
    $("#id_username").on("input",function () {
        //取到用户填写的值
        var username = $(this).val();
        //发请求
        $.ajax({
            url:"/check_username_exist/",
            type:"get",
            data:{"username":username},
            success:function (data) {
                if (data.status){
                    // 用户名已经被注册
                    $("#id_username").next().text(data.msg).parent().addClass("has-error");

                }

            }
        })
    })
</script>

</body>
</html>